// Datos simulados para la aplicación
export const MOCK_USERS = [
  {
    id: "1",
    email: "galilea.serrano@uniguajira.edu.co",
    password: "123456",
    firstName: "Galilea",
    lastName: "Serrano",
    secondLastName: "Ruiz",
    name: "Dra. Galilea Serrano Ruiz",
    role: "teacher",
    assignedLabs: ["lab1", "lab2"],
    photo: require('../assets/images/galla2.jpg'),
  },
  {
    id: "2",
    email: "admin@uniguajira.edu.co",
    password: "admin123",
    firstName: "Carlos",
    lastName: "Rosales",
    secondLastName: "Sanchez",
    name: "Ing. Carlos Rosales Sanchez",
    role: "admin",
    photo: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "3",
    email: "gael.ceballos@uniguajira.edu.co",
    password: "123456",
    firstName: "Gael",
    lastName: "Ceballos",
    secondLastName: "Nava",
    name: "Ing. Gael Ceballos Nava",
    role: "teacher",
    assignedLabs: ["lab3"],
    photo: require('../assets/images/gaelformal.jpg'),
  },
  {
    id: "4",
    email: "jocelin.martinez@uniguajira.edu.co",
    password: "123456",
    firstName: "Jocelin",
    lastName: "Martinez",
    secondLastName: "Mejia",
    name: "Dra. Jocelin Martinez Mejia",
    role: "teacher",
    assignedLabs: ["lab1", "lab3"],
    photo: require('../assets/images/jocelinfoto.jpg'),
  
  },
]

export const MOCK_LABS = [
  {
    id: "lab1",
    name: "Laboratorio de Física Eléctrica y de Ondas",
    description: "Laboratorio equipado para prácticas de mecánica y termodinámica",
    capacity: 30,
    isActive: false,
    activeTeacher: null,
    lights: [
      {
        id: "eb60007e1dd10c2a94ylj6",
        name: "Foco Mesa 1",
        position: { x: 1, y: 1 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
      {
        id: "ebea478e587ff3b4e3xphk",
        name: "Foco Mesa 2",
        position: { x: 1, y: 2 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
      {
        id: "ebb9f6ba0f123c65bftm38",
        name: "Foco Mesa 3",
        position: { x: 2, y: 1 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
      {
        id: "ebce9bd65682fdb7c4qlmf",
        name: "Foco Mesa 4",
        position: { x: 2, y: 2 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
    ],
  },
  {
    id: "lab2",
    name: "Laboratorio de  Óptica",
    description: "Laboratorio especializado en síntesis y análisis orgánico",
    capacity: 25,
    isActive: false,
    activeTeacher: null,
    lights: [
      {
        id: "light6",
        name: "Foco Campana 1",
        position: { x: 1, y: 1 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
      {
        id: "light7",
        name: "Foco Campana 2",
        position: { x: 2, y: 1 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
      {
        id: "light8",
        name: "Foco Central",
        position: { x: 1.5, y: 2 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
    ],
  },
  {
    id: "lab3",
    name: "Laboratorio de Física Mecánica",
    description: "Laboratorio para análisis genético y biología celular",
    capacity: 20,
    isActive: false,
    activeTeacher: null,
    lights: [
      {
        id: "light9",
        name: "Foco Microscopios",
        position: { x: 1, y: 1 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
      {
        id: "light10",
        name: "Foco Preparación",
        position: { x: 2, y: 1 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
      {
        id: "light11",
        name: "Foco Incubadora",
        position: { x: 1.5, y: 2 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
    ],
  },
]

export const MOCK_PRACTICES = [
  {
    id: "practice1",
    name: "Espectroscopia Básica",
    labId: "lab1",
    lights: [
      { lightId: "light1", isOn: true, color: "#FF0000", intensity: 80 },
      { lightId: "light2", isOn: true, color: "#FF0000", intensity: 80 },
      { lightId: "light3", isOn: false, color: "#FFFFFF", intensity: 100 },
      { lightId: "light4", isOn: false, color: "#FFFFFF", intensity: 100 },
      { lightId: "light5", isOn: true, color: "#FF0000", intensity: 60 },
    ],
    isCustom: false,
  },
  {
    id: "practice2",
    name: "Fotosíntesis",
    labId: "lab3",
    lights: [
      { lightId: "light9", isOn: true, color: "#00FF00", intensity: 60 },
      { lightId: "light10", isOn: true, color: "#00FF00", intensity: 60 },
      { lightId: "light11", isOn: true, color: "#00FF00", intensity: 80 },
    ],
    isCustom: false,
  },
  {
    id: "practice3",
    name: "Análisis Químico",
    lights: [
      { lightId: "light6", isOn: true, color: "#0000FF", intensity: 90 },
      { lightId: "light7", isOn: true, color: "#0000FF", intensity: 90 },
      { lightId: "light8", isOn: true, color: "#0000FF", intensity: 70 },
    ],
    isCustom: false,
  },
]

export const RGB_COLORS = [
  { name: "Rojo", value: "#FF0000" },
  { name: "Verde", value: "#00FF00" },
  { name: "Azul", value: "#0000FF" },
  { name: "Amarillo", value: "#FFFF00" },
  { name: "Magenta", value: "#FF00FF" },
  { name: "Cian", value: "#00FFFF" },
  { name: "Blanco", value: "#FFFFFF" },
  { name: "Naranja", value: "#FFA500" },
  { name: "Violeta", value: "#8A2BE2" },
  { name: "Rosa", value: "#FFC0CB" },
  { name: "Lima", value: "#32CD32" },
  { name: "Turquesa", value: "#40E0D0" },
]

