// Datos simulados para la aplicación
export const MOCK_USERS = [
  {
    id: "1",
    email: "carlos.mendoza@uniguajira.edu.co",
    password: "123456",
    firstName: "Carlos",
    lastName: "Mendoza",
    secondLastName: "García",
    name: "Dr. Carlos Mendoza García",
    role: "teacher",
    assignedLabs: ["lab1", "lab2"],
    photo: "/placeholder.svg?height=100&width=100",
    phone: "+57 300 123 4567",
    department: "Física",
  },
  {
    id: "2",
    email: "admin@uniguajira.edu.co",
    password: "admin123",
    firstName: "María",
    lastName: "González",
    secondLastName: "Rodríguez",
    name: "Ing. María González Rodríguez",
    role: "admin",
    photo: "/placeholder.svg?height=100&width=100",
    phone: "+57 300 987 6543",
    department: "Administración",
  },
  {
    id: "3",
    email: "ana.rodriguez@uniguajira.edu.co",
    password: "123456",
    firstName: "Ana",
    lastName: "Rodríguez",
    secondLastName: "López",
    name: "Dra. Ana Rodríguez López",
    role: "teacher",
    assignedLabs: ["lab3"],
    photo: "/placeholder.svg?height=100&width=100",
    phone: "+57 300 555 1234",
    department: "Biología",
  },
  {
    id: "4",
    email: "luis.martinez@uniguajira.edu.co",
    password: "123456",
    firstName: "Luis",
    lastName: "Martínez",
    secondLastName: "Pérez",
    name: "Dr. Luis Martínez Pérez",
    role: "teacher",
    assignedLabs: ["lab1", "lab3"],
    photo: "/placeholder.svg?height=100&width=100",
    phone: "+57 300 777 8888",
    department: "Química",
  },
]

export const MOCK_LABS = [
  {
    id: "lab1",
    name: "Laboratorio de Física I",
    description: "Laboratorio equipado para prácticas de mecánica y termodinámica",
    building: "Bloque A",
    floor: "2do Piso",
    room: "A-201",
    capacity: 30,
    isActive: false,
    activeTeacher: null,
    lights: [
      {
        id: "light1",
        name: "Foco Mesa 1",
        ip: "192.168.1.101",
        position: { x: 1, y: 1 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
      {
        id: "light2",
        name: "Foco Mesa 2",
        ip: "192.168.1.102",
        position: { x: 1, y: 2 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
      {
        id: "light3",
        name: "Foco Mesa 3",
        ip: "192.168.1.103",
        position: { x: 2, y: 1 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
      {
        id: "light4",
        name: "Foco Mesa 4",
        ip: "192.168.1.104",
        position: { x: 2, y: 2 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
      {
        id: "light5",
        name: "Foco Central",
        ip: "192.168.1.105",
        position: { x: 1.5, y: 1.5 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
    ],
  },
  {
    id: "lab2",
    name: "Laboratorio de Química Orgánica",
    description: "Laboratorio especializado en síntesis y análisis orgánico",
    building: "Bloque B",
    floor: "1er Piso",
    room: "B-105",
    capacity: 25,
    isActive: false,
    activeTeacher: null,
    lights: [
      {
        id: "light6",
        name: "Foco Campana 1",
        ip: "192.168.1.201",
        position: { x: 1, y: 1 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
      {
        id: "light7",
        name: "Foco Campana 2",
        ip: "192.168.1.202",
        position: { x: 2, y: 1 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
      {
        id: "light8",
        name: "Foco Central",
        ip: "192.168.1.203",
        position: { x: 1.5, y: 2 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
    ],
  },
  {
    id: "lab3",
    name: "Laboratorio de Biología Molecular",
    description: "Laboratorio para análisis genético y biología celular",
    building: "Bloque C",
    floor: "3er Piso",
    room: "C-301",
    capacity: 20,
    isActive: false,
    activeTeacher: null,
    lights: [
      {
        id: "light9",
        name: "Foco Microscopios",
        ip: "192.168.1.301",
        position: { x: 1, y: 1 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
      {
        id: "light10",
        name: "Foco Preparación",
        ip: "192.168.1.302",
        position: { x: 2, y: 1 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
      {
        id: "light11",
        name: "Foco Incubadora",
        ip: "192.168.1.303",
        position: { x: 1.5, y: 2 },
        isOn: false,
        color: "#FFFFFF",
        intensity: 100,
      },
    ],
  },
]

export const MOCK_PRACTICES = [
  {
    id: "practice1",
    name: "Espectroscopia Básica",
    description: "Análisis de espectros de absorción y emisión",
    color: "#FF0000",
    intensity: 80,
    isCustom: false,
  },
  {
    id: "practice2",
    name: "Fotosíntesis",
    description: "Estudio de procesos fotosintéticos con luz verde",
    color: "#00FF00",
    intensity: 60,
    isCustom: false,
  },
  {
    id: "practice3",
    name: "Análisis Químico",
    description: "Identificación de compuestos con luz azul",
    color: "#0000FF",
    intensity: 90,
    isCustom: false,
  },
]

export const RGB_COLORS = [
  { name: "Rojo", value: "#FF0000" },
  { name: "Verde", value: "#00FF00" },
  { name: "Azul", value: "#0000FF" },
  { name: "Amarillo", value: "#FFFF00" },
  { name: "Magenta", value: "#FF00FF" },
  { name: "Cian", value: "#00FFFF" },
  { name: "Blanco", value: "#FFFFFF" },
  { name: "Naranja", value: "#FFA500" },
  { name: "Violeta", value: "#8A2BE2" },
  { name: "Rosa", value: "#FFC0CB" },
  { name: "Lima", value: "#32CD32" },
  { name: "Turquesa", value: "#40E0D0" },
]

export const BUILDINGS = [
  { id: "A", name: "Bloque A - Ciencias Básicas" },
  { id: "B", name: "Bloque B - Química" },
  { id: "C", name: "Bloque C - Biología" },
  { id: "D", name: "Bloque D - Física" },
  { id: "E", name: "Bloque E - Ingeniería" },
]

export const DEPARTMENTS = ["Física", "Química", "Biología", "Matemáticas", "Ingeniería", "Administración"]
